### ISSUE TITLE
Add theme to vim-airline-themes repo

### ISSUE THREAD

**Issue by pard68** [sainnhe/vim-color-forest-night#16]
Would be nice if this theme existed over [here](https://github.com/vim-airline/vim-airline-themes)

I can/would do it but I thought I should open an issue first before submitting a PR for your theme.

**Comment by sainnhe** [comment]
Thanks for your suggestion.

Sorry but I don't want to add this theme to [vim-airline/vim-airline-themes](https://github.com/vim-airline/vim-airline-themes) because that will be very hard to maintain airline theme for me.

This color scheme is currently far from finished, many designs may be changed in the future.
